packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  '@types/node': ^24
  typescript: ^6.0.0
  vite: npm:@voidzero-dev/vite-plus-core@0.2.1
  vitest: npm:@voidzero-dev/vite-plus-test@0.1.24
  vite-plus: 0.1.24
  '@kazupon/vp-config': ^0.5.0
  wasm-pack: 0.15.0
  bumpp: ^11.1.0
  gh-changelogen: ^0.2.8
  pkg-pr-new: 0.0.75
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
allowBuilds:
  wasm-pack: true
