import { defineConfig } from 'vite-plus'
import {
  defineLintConfig,
  defineFmtConfig,
  defaultIgnoreFilesOfEnforceHeaderCommentRule
} from '@kazupon/vp-config'

export default defineConfig({
  staged: {
    '*': 'vp check --fix'
  },
  test: {
    exclude: ['**/node_modules/**', '**/.git/**', 'refers/**']
  },
  fmt: defineFmtConfig({
    ignorePatterns: ['CHANGELOG.md', 'refers/**']
  }),
  lint: defineLintConfig({
    ignorePatterns: ['refers/**'],
    jsPlugins: [{ name: 'vite-plus', specifier: 'vite-plus/oxlint-plugin' }],
    rules: {
      'vite-plus/prefer-vite-plus-imports': 'error'
    },
    comments: {
      enForceHeaderComment: {
        ignoreFiles: [
          ...defaultIgnoreFilesOfEnforceHeaderCommentRule,
          'apps/**', // NOTE(kazupon): apps/** is generated by vite-plus scaffolding, so we ignore it.
          'packages/cli/bin/**', // NOTE(kazupon): CLI bin files must keep shebangs on the first line.
          'refers/**',
          'tools/**',
          '**/tests/**',
          '**/scripts/**'
        ]
      }
    },
    jsdoc: {
      typescript: 'syntax',
      error: true
    },
    regexp: {}
  })
})
