import { defineConfig } from 'vite-plus'
import {
  defineLintConfig,
  defineFmtConfig,
  defaultIgnoreFilesOfEnforceHeaderCommentRule
} from '@kazupon/vp-config'

export default defineConfig({
  staged: {
    '*': 'vp check --fix'
  },
  fmt: defineFmtConfig({
    ignorePatterns: ['CHANGELOG.md']
  }),
  lint: Object.assign(
    {
      jsPlugins: [{ name: 'vite-plus', specifier: 'vite-plus/oxlint-plugin' }],
      rules: { 'vite-plus/prefer-vite-plus-imports': 'error' }
    },
    defineLintConfig({
      comments: {
        enForceHeaderComment: {
          ignoreFiles: [
            ...defaultIgnoreFilesOfEnforceHeaderCommentRule,
            'apps/**', // NOTE(kazupon): apps/** is generated by vite-plus scaffolding, so we ignore it.
            'packages/**' // NOTE(kazupon): packages/** is generated by vite-plus scaffolding, so we ignore it.
          ]
        }
      },
      jsdoc: {
        typescript: 'syntax',
        error: true
      },
      regexp: {}
    })
  ),
  run: {
    cache: true
  }
})
