import { defineConfig } from 'vite-plus'
import {
  defineLintConfig,
  defineFmtConfig,
  defaultIgnoreFilesOfEnforceHeaderCommentRule
} from '@kazupon/vp-config'

const lintConfig = defineLintConfig({
  comments: {
    enForceHeaderComment: {
      ignoreFiles: [
        ...defaultIgnoreFilesOfEnforceHeaderCommentRule,
        'apps/**', // NOTE(kazupon): apps/** is generated by vite-plus scaffolding, so we ignore it.
        'packages/**', // NOTE(kazupon): packages/** is generated by vite-plus scaffolding, so we ignore it.
        'refers/**',
        'tools/**'
      ]
    }
  },
  jsdoc: {
    typescript: 'syntax',
    error: true
  },
  regexp: {}
})

export default defineConfig({
  staged: {
    '*': 'vp check --fix'
  },
  fmt: defineFmtConfig({
    ignorePatterns: ['CHANGELOG.md', 'refers/**']
  }),
  lint: {
    ...lintConfig,
    ignorePatterns: [...(lintConfig.ignorePatterns ?? []), 'refers/**'],
    jsPlugins: [
      ...(lintConfig.jsPlugins ?? []),
      { name: 'vite-plus', specifier: 'vite-plus/oxlint-plugin' }
    ],
    rules: {
      ...lintConfig.rules,
      'vite-plus/prefer-vite-plus-imports': 'error'
    }
  },
  test: {
    exclude: ['**/node_modules/**', '**/.git/**', 'refers/**']
  },
  run: {
    cache: true
  }
})
