[package]
name = "intlify_linker"
version = "0.14.0-alpha.11"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[features]
default = []
benchmark = []

[lints]
workspace = true

[dependencies]
intlify_contract = { path = "../intlify_contract" }
