import { expect, test } from 'vite-plus/test'

import { validateReleaseChangelog } from './check-release-changelog.mjs'

const releaseUrl = tag => `https://github.com/intlify/intlify/releases/tag/${tag}`

test('accepts a generated stable release entry', () => {
  const tag = 'v1.0.0'
  const source = [
    `# ${tag} (2026-08-10T00:00:00Z)`,
    '',
    `This changelog is generated by [GitHub Releases](${releaseUrl(tag)})`,
    '',
    '**Full Changelog**: https://github.com/intlify/intlify/compare/v0.9.0...v1.0.0',
    ''
  ].join('\n')

  expect(() => validateReleaseChangelog(source, tag)).not.toThrow()
})

test('keeps stable and prerelease entries distinct', () => {
  const stableTag = 'v1.0.0'
  const prereleaseTag = 'v1.0.0-beta.0'
  const source = [
    `# ${stableTag} (2026-08-10T00:00:00Z)`,
    '',
    `[stable](${releaseUrl(stableTag)})`,
    '',
    `# ${prereleaseTag} (2026-08-09T00:00:00Z)`,
    '',
    `[beta](${releaseUrl(prereleaseTag)})`,
    ''
  ].join('\n')

  expect(() => validateReleaseChangelog(source, stableTag)).not.toThrow()
  expect(() => validateReleaseChangelog(source, prereleaseTag)).toThrow()
})

test('accepts a generated prerelease entry', () => {
  const tag = 'v1.0.0-beta.0'
  const source = [
    `# ${tag} (2026-08-10T00:00:00.000Z)`,
    '',
    `[prerelease](${releaseUrl(tag)})`,
    ''
  ].join('\n')

  expect(() => validateReleaseChangelog(source, tag)).not.toThrow()
})

test.each([
  ['missing entry', '# v0.9.0 (2026-08-09T00:00:00Z)\n'],
  [
    'duplicate entry',
    [
      '# v1.0.0 (2026-08-10T00:00:00Z)',
      '',
      `[one](${releaseUrl('v1.0.0')})`,
      '',
      '# v1.0.0 (2026-08-10T00:00:00Z)',
      '',
      `[two](${releaseUrl('v1.0.0')})`,
      ''
    ].join('\n')
  ],
  [
    'malformed duplicate entry',
    [
      '# v1.0.0 (2026-08-10T00:00:00Z)',
      '',
      `[one](${releaseUrl('v1.0.0')})`,
      '',
      '# v1.0.0 (today)',
      ''
    ].join('\n')
  ],
  [
    'wrong release URL',
    '# v1.0.0 (2026-08-10T00:00:00Z)\n\n[release](https://github.com/intlify/intlify/releases/tag/v0.9.0)\n'
  ],
  [
    'malformed heading',
    '# v1.0.0\n\n[release](https://github.com/intlify/intlify/releases/tag/v1.0.0)\n'
  ],
  [
    'malformed timestamp',
    '# v1.0.0 (today)\n\n[release](https://github.com/intlify/intlify/releases/tag/v1.0.0)\n'
  ],
  [
    'release URL outside the first entry',
    [
      '# v1.0.0 (2026-08-10T00:00:00Z)',
      '',
      'No release link here.',
      '',
      '# v0.9.0 (2026-08-09T00:00:00Z)',
      '',
      `[old link](${releaseUrl('v1.0.0')})`,
      ''
    ].join('\n')
  ]
])('rejects %s', (_name, source) => {
  expect(() => validateReleaseChangelog(source, 'v1.0.0')).toThrow()
})

test('rejects a non-semver release tag', () => {
  expect(() => validateReleaseChangelog('# latest (today)', 'latest')).toThrow('strict semver')
})

test.each(['v01.0.0', 'v1.0.0-01'])('rejects non-strict semver tag %s', tag => {
  expect(() => validateReleaseChangelog(`# ${tag} (2026-08-10T00:00:00Z)`, tag)).toThrow(
    'strict semver'
  )
})
