// @license MIT
// @author kazuya kawaguchi (a.k.a. kazupon)

use std::fs;
use std::io;
use std::path::Path;

use schemars::generate::SchemaSettings;
use serde_json::Value;

use crate::config::ProjectConfigFile;

pub const OUTPUT_SCHEMA_VERSION: &str = "0";
pub const CONFIG_SCHEMA_ARTIFACT: &str = "packages/cli/schema/config.schema.json";

#[derive(Debug)]
pub enum ConfigSchemaError {
    Generate(serde_json::Error),
    Read(io::Error),
    Write(io::Error),
    Stale { expected: String, actual: String },
}

impl std::fmt::Display for ConfigSchemaError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Generate(error) => write!(formatter, "failed to generate config schema: {error}"),
            Self::Read(error) => write!(formatter, "failed to read config schema: {error}"),
            Self::Write(error) => write!(formatter, "failed to write config schema: {error}"),
            Self::Stale { .. } => write!(formatter, "committed config schema is stale"),
        }
    }
}

impl std::error::Error for ConfigSchemaError {}

pub fn generate_config_schema() -> Result<String, ConfigSchemaError> {
    let generator = SchemaSettings::draft07().into_generator();
    let root_schema = generator.into_root_schema_for::<ProjectConfigFile>();
    let mut value = serde_json::to_value(root_schema).map_err(ConfigSchemaError::Generate)?;
    remove_schema_id(&mut value);
    remove_nullable_schema_metadata(&mut value);

    let mut output = serde_json::to_string_pretty(&value).map_err(ConfigSchemaError::Generate)?;
    // Keep generated bytes aligned with the repository JSON formatter.
    output = compact_string_enums(&output);
    output.push('\n');
    Ok(output)
}

pub fn write_config_schema(path: &Path) -> Result<(), ConfigSchemaError> {
    let schema = generate_config_schema()?;
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(ConfigSchemaError::Write)?;
    }
    fs::write(path, schema).map_err(ConfigSchemaError::Write)
}

pub fn check_config_schema(path: &Path) -> Result<(), ConfigSchemaError> {
    let expected = generate_config_schema()?;
    let actual = fs::read_to_string(path)
        .map_err(ConfigSchemaError::Read)
        .map(|content| content.replace("\r\n", "\n"))?;

    if actual == expected {
        Ok(())
    } else {
        Err(ConfigSchemaError::Stale { expected, actual })
    }
}

pub fn check_config_schema_contents(actual: &str) -> Result<(), ConfigSchemaError> {
    let expected = generate_config_schema()?;
    let actual = actual.replace("\r\n", "\n");

    if actual == expected {
        Ok(())
    } else {
        Err(ConfigSchemaError::Stale { expected, actual })
    }
}

fn remove_schema_id(value: &mut Value) {
    if let Some(object) = value.as_object_mut() {
        object.remove("$id");
    }
}

fn remove_nullable_schema_metadata(value: &mut Value) {
    let Some(properties) = value
        .as_object_mut()
        .and_then(|object| object.get_mut("properties"))
        .and_then(Value::as_object_mut)
    else {
        return;
    };
    let Some(schema_property) = properties.get_mut("$schema").and_then(Value::as_object_mut) else {
        return;
    };

    schema_property.insert("type".to_owned(), Value::String("string".to_owned()));
    remove_property_null_variant(properties, "fmt");
    remove_property_null_variant(properties, "lint");
}

fn remove_property_null_variant(properties: &mut serde_json::Map<String, Value>, property: &str) {
    let Some(property_schema) = properties.get_mut(property).and_then(Value::as_object_mut) else {
        return;
    };
    let Some(any_of) = property_schema
        .remove("anyOf")
        .and_then(|value| value.as_array().cloned())
    else {
        return;
    };
    let Some(non_null_schema) = any_of
        .into_iter()
        .find(|schema| schema.get("type").and_then(Value::as_str) != Some("null"))
    else {
        return;
    };
    let Some(non_null_schema) = non_null_schema.as_object() else {
        return;
    };

    for (key, value) in non_null_schema {
        property_schema.insert(key.clone(), value.clone());
    }
}

fn compact_string_enums(output: &str) -> String {
    let lines = output.lines().collect::<Vec<_>>();
    let mut compacted = Vec::with_capacity(lines.len());
    let mut index = 0;

    while let Some(line) = lines.get(index) {
        let trimmed = line.trim_start();
        if trimmed == "\"enum\": [" {
            if let Some((next_index, compacted_line)) = compact_enum_lines(&lines, index) {
                compacted.push(compacted_line);
                index = next_index;
                continue;
            }
        }

        compacted.push((*line).to_owned());
        index += 1;
    }

    compacted.join("\n")
}

fn compact_enum_lines(lines: &[&str], start: usize) -> Option<(usize, String)> {
    let line = lines[start];
    let trimmed = line.trim_start();
    let indent = &line[..line.len() - trimmed.len()];
    let mut values = Vec::new();
    let mut cursor = start + 1;

    while let Some(line) = lines.get(cursor) {
        let trimmed = line.trim();
        let trailing_comma = trimmed.ends_with(',');
        let value = trimmed.strip_suffix(',').unwrap_or(trimmed);

        if value == "]" {
            if values.is_empty() {
                return None;
            }
            let joined = values
                .iter()
                .map(|value| {
                    serde_json::to_string(value).expect("string enum value is serializable")
                })
                .collect::<Vec<_>>()
                .join(", ");
            let comma = if trailing_comma { "," } else { "" };
            return Some((cursor + 1, format!("{indent}\"enum\": [{joined}]{comma}")));
        }

        match serde_json::from_str::<String>(value) {
            Ok(value) => values.push(value),
            Err(_) => return None,
        }
        cursor += 1;
    }

    None
}
